name:                blockchain-in-haskell
version:             0.1.0.0
github:              githubuser/blockchain-in-haskell
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/blockchain-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- time
- bytestring
- protolude
- cryptonite
- vector
- binary
- memory
- base16-bytestring
- directory
# Data.Map
- containers

library:
  source-dirs: src

executables:
  blockchain-in-haskell-new:
    main:                New.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-in-haskell

executables:
  blockchain-in-haskell-mine:
    main:                Mine.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-in-haskell

executables:
  blockchain-in-haskell-list-balances:
    main:                ListBalances.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-in-haskell

tests:
  blockchain-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-in-haskell
